/**
 * Enrich existing ClientProject descriptions with LONG, SEO-optimized
 * case studies generated by the z-ai LLM (reuses the server lib).
 * The original short description is passed to the AI as "hints" so the
 * real project details (materials, deliverables) are kept in the story.
 *
 * Run (batches, idempotent — already-long projects are skipped):
 *   bun scripts/enrich-project-descriptions.ts [limit]
 */
import { db } from "../src/lib/db";
import { generateProjectDescription } from "../src/lib/describe-project";

function countWords(s: string): number {
  return s.split(/\s+/).filter(Boolean).length;
}

async function main() {
  const limit = Number(process.argv[2] ?? 6);

  const clients = await db.client.findMany({
    include: { projects: true },
    orderBy: { sortOrder: "asc" },
  });

  // flatten: [client, project] pairs still needing a long description
  const pending: { clientId: string; clientName: string; industry: string | null; project: { id: string; title: string; description: string; year: number | null } }[] = [];
  for (const c of clients) {
    for (const p of c.projects) {
      if (countWords(p.description) < 200) {
        pending.push({
          clientId: c.id,
          clientName: c.name,
          industry: c.industry,
          project: { id: p.id, title: p.title, description: p.description, year: p.year },
        });
      }
    }
  }

  console.log(`Projects needing a long SEO description: ${pending.length} (processing up to ${limit} this run)`);

  let done = 0;
  for (const item of pending) {
    if (done >= limit) break;
    console.log(`\n[${done + 1}/${Math.min(limit, pending.length)}] ${item.clientName} — "${item.project.title}"…`);
    try {
      const res = await generateProjectDescription({
        clientName: item.clientName,
        clientIndustry: item.industry,
        title: item.project.title,
        year: item.project.year,
        hints: item.project.description, // original short text = ground truth for the AI
      });
      await db.clientProject.update({
        where: { id: item.project.id },
        data: { description: res.description },
      });
      console.log(`  ✓ ${res.method} · ${res.wordCount} words · ${res.keywords.slice(0, 3).join(", ")}`);
      done++;
    } catch (e) {
      console.error(`  ✗ failed:`, e instanceof Error ? e.message : e);
    }
  }

  const remaining = pending.length - done;
  console.log(`\nDone. Enriched ${done} project(s). ${remaining > 0 ? `${remaining} remaining — run again.` : "All projects have long SEO descriptions."}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
